
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Use environment variables or fallback to build-time constants for production
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://kzejmozxbhzkrbfmwmnx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt6ZWptb3p4Ymh6a3JiZm13bW54Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1Mzc3MzMsImV4cCI6MjA2NzExMzczM30.dvMHh8cLAeYRbalHsA8x1QUI36nWP-xgkws11vnrKdI";

console.log('Supabase client initialization - URL:', SUPABASE_URL);
console.log('Supabase client initialization - Key exists:', !!SUPABASE_PUBLISHABLE_KEY);

// Validate required configuration
if (!SUPABASE_URL) {
  console.error('SUPABASE_URL is missing or undefined:', SUPABASE_URL);
  throw new Error('Missing Supabase URL. Please check your configuration.');
}

if (!SUPABASE_PUBLISHABLE_KEY) {
  console.error('SUPABASE_PUBLISHABLE_KEY is missing or undefined:', SUPABASE_PUBLISHABLE_KEY);
  throw new Error('Missing Supabase publishable key. Please check your configuration.');
}

console.log('Creating Supabase client with URL:', SUPABASE_URL);

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    // Security enhancement: Add session timeout
    detectSessionInUrl: true,
    flowType: 'pkce'
  },
  // Security enhancement: Add request timeout
  global: {
    headers: {
      'X-Client-Info': 'employee-management-app'
    }
  }
});

console.log('Supabase client created successfully');
