// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bdprgxdvzjhxsthkgnbs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJkcHJneGR2empoeHN0aGtnbmJzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5NzUxNzcsImV4cCI6MjA2NzU1MTE3N30.ZCnbk65ITv2TAkFoJsJwShfIfo_QjR860RkuBIB4y3w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});